[options]
  colorscheme = "ayu"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'shell'

[[custom_plugins]]
  name = "curry/ayu-vim"
  merged = 0

[[custom_plugins]]
  name = "vim-scripts/dbext.vim"
  merged = 0
